import * as pdfjs from './vendor/pdf.min.mjs';
pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.min.mjs',import.meta.url).href;
const $=id=>document.getElementById(id);
let slides=[],pdf=null,index=0,total=0,elapsed=0,running=false,last=performance.now(),renderTask=null,renderToken=0,loading=false;
const xml=s=>new DOMParser().parseFromString(s,'application/xml');
const textNodes=(doc,tag)=>[...doc.getElementsByTagNameNS('*',tag)].map(n=>n.textContent);
const status=(s,error=false)=>{$('status').textContent=s;$('status').classList.toggle('error',error)};
const route=()=>slides.map((s,i)=>i).filter(i=>!$('routeOnly').checked||slides[i].included);
const newSlide=(title,text='',notes='')=>({title,text,notes,cue:'',transition:'',question:'Why does this point matter to your audience, and what supports it?',answer:'',evidenceNote:'',included:true});
function save(){if(!slides.length)return;for(const k of ['cue','transition','question','answer','evidenceNote'])slides[index][k]=$(k).value}
function clocks(){const now=performance.now();if(running){const dt=(now-last)/1000;total+=dt;elapsed+=dt}last=now;const fmt=n=>Math.floor(n/60).toString().padStart(2,'0')+':'+Math.floor(n%60).toString().padStart(2,'0');$('total').textContent=fmt(total);$('elapsed').textContent=fmt(elapsed);const count=slides.filter(s=>s.included).length;const target=Number($('minutes').value)*60/Math.max(count,1);$('elapsed').classList.toggle('over',elapsed>target);$('total').classList.toggle('over',total>Number($('minutes').value)*60);$('pace').textContent=count?`${count} slides in your speaking route · ${Math.round(target)} seconds per slide as a starting guide. Give key slides more time.`:'No slides included in your speaking route.'}
function reset(){running=false;total=elapsed=0;last=performance.now();$('start').textContent='Start timer';clocks()}
function options(){const r=route();$('jump').replaceChildren(...r.map(i=>{const o=document.createElement('option');o.value=i;o.textContent=`${i+1} · ${slides[i].title}`;return o}));$('jump').value=index;const pos=r.indexOf(index);$('prev').disabled=pos<=0;$('next').disabled=pos<0||pos>=r.length-1;$('ending').hidden=!(r.length&&pos===r.length-1)}
async function draw(){const s=slides[index];if(!s)return;const token=++renderToken;$('title').textContent=s.title;$('count').textContent=`· ${index+1} / ${slides.length}`;for(const k of ['cue','transition','question','answer','evidenceNote'])$(k).value=s[k];$('included').checked=s.included;$('source').textContent=`SLIDE TEXT\n${s.text||'No extractable text. Read the slide image.'}\n\nSPEAKER NOTES\n${s.notes||'No speaker notes imported. Pair a PowerPoint to bring them in.'}`;$('answerbox').open=false;options();clocks();if(renderTask){renderTask.cancel();renderTask=null}if(pdf){$('canvas').hidden=false;$('textslide').hidden=true;try{const page=await pdf.getPage(index+1);if(token!==renderToken)return;const base=page.getViewport({scale:1});const viewport=page.getViewport({scale:Math.min(1600/base.width,2)});const canvas=$('canvas');canvas.width=viewport.width;canvas.height=viewport.height;renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport});await renderTask.promise;if(token===renderToken)renderTask=null}catch(e){if(e.name!=='RenderingCancelledException')status('The slide could not be drawn. Try exporting your presentation to a new PDF.',true)}}else{$('canvas').hidden=true;$('textslide').hidden=false;$('textslide').replaceChildren();const h=document.createElement('h2');h.textContent=s.title;const p=document.createElement('p');p.textContent=s.text;$('textslide').append(h,p)}}
async function readPDF(file){const doc=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false}).promise;if(doc.numPages>200){await doc.destroy();throw Error('Please use a presentation with 200 slides or fewer.')}const items=[];for(let i=1;i<=doc.numPages;i++){status(`Reading slide ${i} of ${doc.numPages}…`);const page=await doc.getPage(i);const tc=await page.getTextContent();const text=tc.items.map(x=>x.str+(x.hasEOL?'\n':' ')).join('').trim();items.push(newSlide(text.split('\n').find(x=>x.trim())?.slice(0,100)||`Slide ${i}`,text))}return {items,doc}}
async function readPPTX(file){const zip=await JSZip.loadAsync(file);let expanded=0;for(const entry of Object.values(zip.files)){expanded+=entry._data?.uncompressedSize||0;if(expanded>150*1024*1024)throw Error('This PowerPoint expands beyond the supported size. Export it to PDF.')}const presentation=zip.file('ppt/presentation.xml');const rels=zip.file('ppt/_rels/presentation.xml.rels');if(!presentation||!rels)throw Error('This is not a readable PowerPoint presentation.');const links=xml(await rels.async('string'));const map=Object.fromEntries([...links.getElementsByTagNameNS('*','Relationship')].map(n=>[n.getAttribute('Id'),n.getAttribute('Target')]));const ids=[...xml(await presentation.async('string')).getElementsByTagNameNS('*','sldId')];if(!ids.length||ids.length>200)throw Error('Please use a presentation with 1–200 slides.');const items=[];for(const id of ids){const rid=id.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id');const target=map[rid];const path=target?.startsWith('/')?target.slice(1):'ppt/'+target;const entry=zip.file(path);if(!entry)throw Error('A slide is missing from this PowerPoint.');const doc=xml(await entry.async('string'));const text=textNodes(doc,'t').join('\n');let notes='';const relpath=path.replace(/([^/]+)$/,'_rels/$1.rels');const rel=zip.file(relpath);if(rel){const nr=[...xml(await rel.async('string')).getElementsByTagNameNS('*','Relationship')].find(n=>n.getAttribute('Type')?.endsWith('/notesSlide'));if(nr){const notePath=new URL(nr.getAttribute('Target'),'https://local/'+path).pathname.slice(1);const nf=zip.file(notePath);if(nf){const nd=xml(await nf.async('string'));notes=[...nd.getElementsByTagNameNS('*','sp')].filter(sp=>{const ph=sp.getElementsByTagNameNS('*','ph')[0];return !ph||!['sldImg','sldNum','hdr','ftr','dt'].includes(ph.getAttribute('type'))}).map(sp=>textNodes(sp,'t').join('\n')).filter(Boolean).join('\n')}}}items.push(newSlide(text.split('\n')[0]?.slice(0,100)||`Slide ${items.length+1}`,text,notes))}return {items,doc:null}}
async function upload(file,pair=false){if(!file||loading)return;loading=true;try{if(file.size>50*1024*1024)throw Error('Please choose a file smaller than 50 MB.');const extension=file.name.split('.').pop().toLowerCase();if(!['pdf','pptx'].includes(extension))throw Error('Choose a PDF or .pptx file.');status('Reading your presentation in this browser…');const result=extension==='pdf'?await readPDF(file):await readPPTX(file);if(pair){if(result.items.length!==slides.length){await result.doc?.destroy();throw Error('The paired file must have the same slide count. Check that both exports are from the same version.')}save();if(extension==='pdf'){if(pdf)await pdf.destroy();pdf=result.doc;slides.forEach((s,i)=>{s.text=result.items[i].text;s.title=result.items[i].title})}else{slides.forEach((s,i)=>{s.notes=result.items[i].notes;if(!pdf){s.text=result.items[i].text;s.title=result.items[i].title}})}}else{if(pdf)await pdf.destroy();pdf=result.doc;slides=result.items;index=0;$('deckname').textContent=file.name;$('routeOnly').checked=false;reset()}$('format').textContent=pdf?'Original PDF visuals · coaching is editable':'PowerPoint text view · pair a PDF for original visuals';deckEpoch++;aiDraft=null;$('suggestions').hidden=true;$('consent').checked=false;$('upload').hidden=true;$('workspace').hidden=false;$('newDeck').hidden=false;status('Presentation ready. Add your cues and start practising.');await draw()}catch(e){status(e.message||'Could not read this file. Try exporting it to PDF.',true)}finally{loading=false;$('file').value='';$('pairfile').value=''}}
$('file').onchange=e=>upload(e.target.files[0]);$('pairfile').onchange=e=>upload(e.target.files[0],true);$('pair').onclick=()=>$('pairfile').click();for(const type of ['dragenter','dragover'])$('drop').addEventListener(type,e=>{e.preventDefault();$('drop').classList.add('drag')});$('drop').addEventListener('dragleave',()=>$('drop').classList.remove('drag'));$('drop').addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('drag');upload(e.dataTransfer.files[0])});
$('demo').onclick=async()=>{if(pdf)await pdf.destroy();pdf=null;slides=[newSlide('A better customer onboarding experience','The opportunity\nCustomers need a clear path from sign-up to their first useful outcome.','Explain the customer problem before proposing a solution.'),newSlide('Three decisions to test','Remove duplicate steps.\nExplain what happens next.\nMeasure completion and time to first value.','These are hypotheses for a fictional example, not verified outcomes.'),newSlide('Agree the next step','Choose one journey.\nTest with customers.\nReview the evidence before scaling.','Close with a concrete request and invite questions.')];slides[0].cue='Help the audience understand the customer’s first hurdle.';slides[0].transition='That gives us three choices to test.';index=0;reset();$('deckname').textContent='Customer onboarding · fictional demo';$('format').textContent='Sample content · no real performance claims';deckEpoch++;aiDraft=null;$('suggestions').hidden=true;$('consent').checked=false;$('upload').hidden=true;$('workspace').hidden=false;$('newDeck').hidden=false;$('routeOnly').checked=false;status('Demo ready. Replace these cues with your own.');draw()};
$('newDeck').onclick=()=>{save();running=false;clocks();$('workspace').hidden=true;$('upload').hidden=false;$('newDeck').hidden=true;status('Save your practice plan before replacing the presentation if you want to keep your notes.')};
function move(i){if(i===undefined||i===index)return;save();clocks();index=i;elapsed=0;draw()}$('prev').onclick=()=>{const r=route();move(r[r.indexOf(index)-1])};$('next').onclick=()=>{const r=route();move(r[r.indexOf(index)+1])};$('jump').onchange=e=>move(Number(e.target.value));$('included').onchange=e=>{slides[index].included=e.target.checked;if($('routeOnly').checked&&!e.target.checked){const r=route();if(r.length)move(r.find(i=>i>index)??r[0]);else $('routeOnly').checked=false}options();clocks()};$('routeOnly').onchange=()=>{if(!route().length){$('routeOnly').checked=false;status('Include at least one slide before practising a speaking route.',true)}if(!route().includes(index))move(route()[0]);options()};$('minutes').onchange=()=>{const n=Number($('minutes').value);$('minutes').value=Math.max(1,Math.min(240,n||10));clocks()};$('start').onclick=()=>{clocks();running=!running;$('start').textContent=running?'Pause timer':'Resume timer'};$('reset').onclick=reset;
for(const k of ['cue','transition','question','answer','evidenceNote'])$(k).oninput=save;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>document.querySelectorAll('[data-tab]').forEach(t=>{t.setAttribute('aria-selected',String(t===b));$(t.dataset.tab).hidden=t!==b}));
$('export').onclick=()=>{save();const content={version:1,name:$('deckname').textContent,targetMinutes:Number($('minutes').value),slides:slides.map(({title,cue,transition,question,answer,evidenceNote,included})=>({title,cue,transition,question,answer,evidenceNote,included}))};const url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='presentation-practice-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Practice plan saved. It contains your notes, not the presentation file. Keep it private if your notes are sensitive.')};
$('planfile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024)throw Error('Practice plans must be smaller than 2 MB.');const p=JSON.parse(await file.text());if(p.version!==1||!Array.isArray(p.slides)||p.slides.length!==slides.length)throw Error('This plan must match the loaded presentation’s slide count.');if(p.slides.some((s,i)=>s.title!==slides[i].title))throw Error('The slide titles differ. Load the presentation version used to save this plan.');for(let i=0;i<slides.length;i++){for(const k of ['cue','transition','question','answer','evidenceNote'])slides[i][k]=typeof p.slides[i][k]==='string'?p.slides[i][k].slice(0,20000):'';slides[i].included=p.slides[i].included!==false}$('minutes').value=Math.max(1,Math.min(240,Number(p.targetMinutes)||10));$('routeOnly').checked=false;draw();status('Practice plan restored.')}catch(e){status(e.message,true)}finally{$('planfile').value=''}};
document.addEventListener('keydown',e=>{if(!slides.length||$('workspace').hidden||['INPUT','TEXTAREA','SELECT','BUTTON','SUMMARY'].includes(document.activeElement.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();$('next').click()}if(e.key==='ArrowLeft'){e.preventDefault();$('prev').click()}if(e.code==='Space'){e.preventDefault();$('start').click()}});setInterval(clocks,200);

let aiDraft=null;let aiSlide=-1;let deckEpoch=0;
$('endpoint').value=window.PRACTICE_CONFIG?.coachEndpoint||'';
$('generate').onclick=async()=>{
 if(!$('consent').checked){$('aiStatus').textContent='Please agree to send this slide’s text and notes before generating coaching.';return}
 let url;try{url=new URL($('endpoint').value);if(url.protocol!=='https:'&&!(['localhost','127.0.0.1'].includes(url.hostname)&&url.protocol==='http:'))throw Error()}catch{$('aiStatus').textContent='Enter the HTTPS URL of your coach service. For local testing, localhost is supported.';return}
 save();const current=index;const epoch=deckEpoch;const s=slides[current];if(!s.text.trim()&&!s.notes.trim()){$('aiStatus').textContent='This slide has no extractable text. Add speaker notes in PowerPoint and pair the file.';return}
 $('generate').disabled=true;$('suggestions').hidden=true;$('aiStatus').textContent='Generating a draft for slide '+(current+1)+'…';
 try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Coach-Access':$('access').value},body:JSON.stringify({audience:$('audience').value.slice(0,500),goal:$('goal').value.slice(0,500),targetMinutes:Number($('minutes').value),slide:{title:s.title,text:s.text.slice(0,12000),notes:s.notes.slice(0,8000)},previous:slides[current-1]?.title||'',next:slides[current+1]?.title||''}),signal:AbortSignal.timeout(90000)});const result=await response.json();if(epoch!==deckEpoch)throw Error('The presentation changed. Generate a new draft for the current deck.');if(!response.ok)throw Error(result.error||'The coaching service is unavailable.');const draft=result.coaching;for(const k of ['cue','transition','question','answer','evidenceNote'])if(typeof draft?.[k]!=='string')throw Error('The coaching response was incomplete. Please try again.');aiDraft=draft;aiSlide=current;$('aiDraft').textContent=['Main message: '+draft.cue,'Transition: '+draft.transition,'Question: '+draft.question,'Answer anchors: '+draft.answer,'Evidence checks: '+draft.evidenceNote].join('\n\n');$('suggestions').hidden=false;$('aiStatus').textContent='Draft ready for slide '+(current+1)+'. Check every claim before applying.';}catch(e){$('aiStatus').textContent=e.name==='TimeoutError'?'The request timed out. Your existing notes are unchanged.':e.message||'Could not reach the AI service. Check its URL and access code.'}finally{$('generate').disabled=false}
};
$('applyAI').onclick=()=>{if(!aiDraft)return;if(index!==aiSlide){$('aiStatus').textContent='Return to slide '+(aiSlide+1)+' to apply this draft.';return}for(const k of ['cue','transition','question','answer','evidenceNote']){slides[index][k]=aiDraft[k];$(k).value=aiDraft[k]}$('suggestions').hidden=true;aiDraft=null;$('aiStatus').textContent='Draft applied. Edit the prompts into your own words.'};
